name: Languages
description: A Flutter app to learn languages
version: 1.0.0+12

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  dafluta: ^2.6.0
  dahttp: ^3.2.0
  flutter_tts: ^1.3.0
  dropdown_search: ^0.4.5
  json_annotation: ^3.1.0
  shared_preferences: ^0.5.12+2

  flutter:
    sdk: flutter

dev_dependencies:
  daassets: ^1.1.1
  dapackages: ^1.3.0
  build_runner: ^1.10.3
  daincrementer: ^1.0.0
  json_serializable: ^3.5.0
  flutter_launcher_icons: ^0.8.1

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher/launcher.png"